[build]
  publish = "./pro_site/dist"
  command = "yarn && yarn bootstrap && yarn build && yarn ui:build && cd packages/umi && yarn link && cd ../.. && git clone https://github.com/ant-design/ant-design-pro --depth=1 pro_site && cd pro_site && yarn && yarn link umi && yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
